version: '3.7'

volumes:
  logs:
    driver: local

services:
  php:
    build:
      context: ./
      dockerfile: ./builder/php.docker
    container_name: "${PROJECT_NAME}_php"
    working_dir: /var/www
    command: php -c /usr/local/etc/php/php.ini-development -S 0.0.0.0:8080 -t ./public
    ports:
      - 8080:8080
    volumes:
      - .:/var/www
      - logs:/var/www/logs
